# Generated by Django 5.1.1 on 2025-04-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section_5",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Indoor Signage", "Indoor Signage"),
                            ("Outdoor Signage", "Outdoor Signage"),
                            ("Vinyl Sticker", "Vinyl Sticker"),
                            ("LED Display", "LED Display"),
                            ("Digital Signage", "Digital Signage"),
                        ],
                        max_length=100,
                    ),
                ),
                ("location", models.CharField(default="Unknown", max_length=255)),
                ("details", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
