# Generated by Django 5.1.1 on 2025-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_section_5_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section_5",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="staticfiles/section_5/"
            ),
        ),
    ]
