# Generated by Django 5.1.1 on 2025-04-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_section_5_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section8",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("client_role", models.CharField(max_length=100)),
                (
                    "client_image",
                    models.ImageField(blank=True, null=True, upload_to="Section8/"),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("message", models.TextField()),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
    ]
