# Generated by Django 5.1.1 on 2025-04-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_section8"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section8",
            name="client_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="staticfiles/Section8/"
            ),
        ),
    ]
